title: "tkf blog"
baseurl: ""
tagline: A crystalline Jekyll theme for blog
description: Just a stupid demo site.
# cover: /cover.jpg
email: teknofile@teknofile.org
url: https://teknofile.org/
skills: "not dieing"
# meta_author: LastName FirstName
#theme: jekyll-theme-architect

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

#remote_theme: startbootstrap/startbootstrap-clean-blog
#remote_theme: y7kim/agency-jekyll-theme

# Build settings
markdown: kramdown
permalink: pretty
